import os

# BOT_TOKEN = os.environ.get("BOT_TOKEN", "")
# API_ID = int(os.environ.get("API_ID", ""))
# API_HASH = os.environ.get("API_HASH", "")
# LOG_CHANNEL = int(os.environ.get("LOG_CHANNEL", ""))
# MUST_JOIN = os.environ.get("MUST_JOIN", "@nrbots")
# AUTH_USERS = set(int(x) for x in os.environ.get("AUTH_USERS", "932498979 5422759678 5399174823 5679956601").split())
# DB_URL = os.environ.get("DB_URL", "")
# DB_NAME = os.environ.get("DB_NAME", "memadder")
# BROADCAST_AS_COPY = bool(os.environ.get("BROADCAST_AS_COPY", False))
# FORCE_SUBS = bool(os.environ.get("FORCE_SUBSCRIBE", False))
# PORT = os.environ.get("PORT", "8080")


BOT_TOKEN = os.environ.get("BOT_TOKEN", "6293841824:AAFrCKXxVoOJkMV1aBDyXXG2fWFGrlE4y90")
API_ID = int(os.environ.get("API_ID", "18140047"))
API_HASH = os.environ.get("API_HASH", "09d25e82864bb21419ef2c1eb4806e9c")
LOG_CHANNEL = int(os.environ.get("LOG_CHANNEL", "-1787723214"))
MUST_JOIN = os.environ.get("MUST_JOIN", -1715599286)
AUTH_USERS = set(int(x) for x in os.environ.get("AUTH_USERS", "5986785549").split())
DB_URL = os.environ.get("DB_URL", "mongodb+srv://dbnora:<password>@atlascluster.gvwwndh.mongodb.net/test")
DB_NAME = os.environ.get("DB_NAME", "memadder")
BROADCAST_AS_COPY = bool(os.environ.get("BROADCAST_AS_COPY", False))
FORCE_SUBS = bool(os.environ.get("FORCE_SUBSCRIBE", False))
PORT = os.environ.get("PORT", "8000")
